# Generated by Django 5.2 on 2025-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0002_hiddengem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hiddengem',
            old_name='description',
            new_name='why_hidden',
        ),
        migrations.RemoveField(
            model_name='hiddengem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hiddengem',
            name='youtube_ideas',
        ),
        migrations.AddField(
            model_name='hiddengem',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hiddengem',
            name='place_name',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
    ]
