# Generated by Django 5.2 on 2025-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage', '0003_rename_description_hiddengem_why_hidden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
    ]
